--- 
- name: Copy generated ec2-keypair for newly created EC2 instances
  hosts: testgroup
  gather_facts: False
  vars:
    ansible_user: ec2-user
    key : "~/.ssh/id_rsa.pub"
  tasks:
    - name: "Copy the authorized key file from"
      authorized_key: 
        user: "{{ansible_user}}"
        state: present
        key: "{{ lookup('file', '{{ key }}')}}"
