---
- hosts: localhost
  become: true
  vars:
    users_with_items:
      - name: "testuser01"
        personal_directories:
          - "conf"
          - "examples"
          - "downloads"
      - name: "testuser02"
        personal_directories:
          - "config"
          - "files"
          - "docs"

    common_directories:
      - ".ssh"
      - "downloads"
      
  tasks:
  - name: create directories
    file:
      dest: "/home/{{item.0.name}}/{{item.1}}"
      owner: "{{ item.0.name }}"
      group: "{{ item.0.name }}"
      state: directory
    with_nested:
      - "{{ users_with_items }}"
      - "{{ common_directories }}"

    
     
