---
- hosts: localhost
  tasks:
  - group:
      name: testgroup
      state: present 
  - user:
      name: "{{ item }}"
      state: present
      groups: "testgroup"
    with_sequence: start=1 end=9 format=testuser%02x
