---
- hosts: localhost
  vars_files:
  - myvars.yml
  tasks:
  - name: Create an EC2 instance
    ec2:
      key_name: "{{key_pair}}"
      region: "{{ region }}"
      group_id: "{{ ansible_sg }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      instance_tags:
        env: "{{ env }}"
        Name: "{{ instance_name }}"
      count_tag: env
      exact_count: "{{ instance_count }}"
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
    register: ec2

  - name: disp
    debug:
      msg: " {{ item.public_ip }}"
    with_items: "{{ ec2.instances }}"
  
  - name: Add the newly created EC2 instance(s) to host group
    lineinfile: dest="{{ hostpath }}"
                regexp="{{ item.private_ip }}"
                insertafter="[webstack]" 
                line="{{ item.private_ip }}"
                state=present
    with_items: "{{ec2.instances}}"
  
  - wait_for: path="{{ hostpath }}"
  
  - name: Wait for SSH to come up
    local_action: wait_for 
                  host="{{ item.public_ip }} "
                  port=22 
                  state=started
    with_items: "{{ec2.instances}}"
