---
# tasks file for common
- name: install common tools
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - curl
    - python-httplib2
    - git
    - wget
    - python-pip
    - python-virtualenv
    - php
