---
- hosts: localhost
  become: true
  gather_facts: no
  roles:
     - ec2

  post_tasks:
    - name: refresh inv
      meta: refresh_inventory

- hosts: mongod-servers
  become: true
  gather_facts: no
  roles:
     - mongodb
