---
- hosts: localhost
  vars_files:
  - myvars.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Create EC2 instance(s) with desired instance_count and instance_name, add new instances to an inventory file under [webstack] group and wait for SSH to come up
    ec2:
      key_name: "{{key_pair}}"
      region: "{{ region }}"
      group_id: "{{ ansible_sg }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      instance_tags:
        env: "{{ env }}"
        Name: "{{ instance_name }}"
      count_tag: env
      exact_count: "{{ instance_count }}"
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
    register: ec2

  - name: disp
    debug:
      msg: " {{ item.public_ip }}"
    with_items: "{{ ec2.instances }}"
  
  - name: Add the newly created EC2 instance(s) to host group
    lineinfile: dest="{{ hostpath }}"
                regexp="{{ item.private_ip }}"
                insertafter="[webstack]" 
                line="{{ item.private_ip }}"
                state=present
    with_items: "{{ec2.instances}}"
  
  - wait_for: path="{{ hostpath }}"
  
  - name: Wait for SSH to come up
    delegate_to: "{{ item.public_ip }} "
    wait_for_connection:
      delay: 60
      timeout: 300 
    loop: "{{ec2.instances}}"
